print ("  EEEEE ")
print ("  E     ")
print ("  EEE   ")
print ("  E     ")
print ("  EEEEE ")
print  ("  SSS  ")
print  (" S   S ")
print  (" S     ")
print  ("  SSS  ")
print  ("     S ")
print  (" S   S ")
print  ("  SSS  ")